### ISSUE TITLE
add a v1 tag, and move it with each v1.x release

### ISSUE THREAD

**Issue by vincent-fuchs** [s4u/setup-maven-action#106]
**Is your feature request related to a problem? Please describe.**

each release is semantically versioned and tag, but there's no `v1` tag, so we can't upgrade automatically to latest changes : we are forced to point to a given version (v1.16.0 at the moment). 

**Describe the solution you'd like**
A lot of other GitHub actions have that pattern of adding a extra tag for the major versions (`v1` for instance), so that people can refer to it instead of a precise version. The day `v1.17.0` is released, `v1` would be moved to the same commit, and people referencing `v1` would start using it immediately

**Comment by slawekjaranowski** [comment]
dependabot, renovate and such other tools can help you, even you want to use the latest version you can point to `main` branch.
