### ISSUE TITLE
Allow proxy configuration

### ISSUE THREAD

**Issue by ahettlin** [s4u/setup-maven-action#62]
It would be great to be able to configure the proxies setting of the maven-settings-action similar to the other settings that are already provided. I've not tried to set it, assuming that if it's not documented it doesn't exist.

Currently, I am unable to use this aggregate action and instead have to call each action individually so I can get access to the proxies setting on s4u/maven-settings-action.

**Comment by slawekjaranowski** [comment]
PR are welcome, as example you can see #52, #58
